### ISSUE TITLE
Converters do not give meaningful error message

### ISSUE THREAD

**Issue by hunterhector** [hunterhector/EvmEval#10]
Current ldc-to-xml converter do not give clear error message at some places. For example, when the "-o" option is not provided, it just throw NullPointerException:

Exception in thread "main" java.lang.NullPointerException
    at java.io.File.<init>(File.java:277)
    at converter.LdcXmlToBratConverter.main(LdcXmlToBratConverter.java:47)

**Comment by hunterhector** [comment]
This is actually pretty similar to the other issue:

https://github.com/hunterhector/EvmEval/issues/8

Basically, try to give useful hints at place of exceptions.
